#!/bin/bash

sudo keadm join --cloudcore-ipport=52.234.39.80:10000 --edgenode-name=$(cat /proc/sys/kernel/hostname) --token=428a365d2cb9010b91e7099bf0a8db1bfb45e7e68fac2fc24ed52d3005895d3c.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3Mzc1NDcxOTl9.mdcDKZdrLzivurZ6MiF_-Fzx7v98AsFvGMfCSqTi3W0 --remote-runtime-endpoint=unix:///run/containerd/containerd.sock --cgroupdriver=systemd --kubeedge-version=v1.16.0

sudo sed -i '/edgeStream/ {N;s/\(enable: \).*/\1true/}' /etc/kubeedge/config/edgecore.yaml
sudo sed -i '/metaServer:/,/enable:/s/\(enable: \).*/\1true/' /etc/kubeedge/config/edgecore.yaml
sudo sed -i '71 a  \\      clusterDNS:' /etc/kubeedge/config/edgecore.yaml
sudo sed -i '72 a  \\      - 169.254.96.16' /etc/kubeedge/config/edgecore.yaml
sudo systemctl restart edgecore.service

echo "Installing helm..."
if ! sudo helm version &> /dev/null; then
    curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
    chmod 700 get_helm.sh
    ./get_helm.sh
    rm -rf get_helm.sh
    sudo helm version
else
    sudo echo "Helm already installed"
fi

echo "Applying telegraf"
if ! command -v telegraf &> /dev/null; then
    sudo echo -e "Installing telegraf..."
    sudo apt install gnupg -y
    sudo apt install lsb-release -y
    sudo apt-get update -y
    cat <<EOF | sudo tee /etc/apt/sources.list.d/influxdata.list
deb https://repos.influxdata.com/ubuntu $(lsb_release -cs) stable
EOF
    sudo curl -fsSL https://repos.influxdata.com/influxdata-archive_compat.key | gpg --dearmor | sudo tee  /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
    sudo curl -sL https://repos.influxdata.com/influxdb.key | sudo apt-key add -
    sudo curl -fsSL https://repos.influxdata.com/influxdata-archive_compat.key | gpg --dearmor | sudo tee  /etc/apt/trusted.gpg.d/influxdata-archive_compat.gpg > /dev/null
    sudo apt update -y
    sudo apt install telegraf=1.26.0-1
    sudo deluser telegraf root
    sudo usermod -aG root telegraf
else
    sudo echo "Telegraf is already installed."
fi

echo 'Finish...'
